# boresight_from_scst.py had a bug where the 'has_aspect' column of
# metadata.parquet was recorded as True for all eclipses.  This script
# corrects the 'has_aspect' column of a metadata.parquet that was
# generated by a boresight_from_scst.py with that bug.

import argparse

from pathlib import Path
from pyarrow import parquet, Table
from pyarrow.compute import invert

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("bad_metadata", type=Path)
    ap.add_argument("fixed_metadata", type=Path)

    args = ap.parse_args()
    bad_table = parquet.read_table(args.bad_metadata)
    names = bad_table.column_names
    columns = bad_table.columns

    # 'has_aspect' should be false whenever 'observed_legs' is null.
    has_aspect_ix = names.index("has_aspect")
    observed_legs_ix = names.index("observed_legs")
    columns[has_aspect_ix] = invert(columns[observed_legs_ix].is_null())

    fixed_table = Table.from_arrays(columns, names)
    parquet.write_table(fixed_table, args.fixed_metadata)

main()
