"""Phase 1 of sky coverage map generation.  Read the aspect table and filter it
down to just the good points.  Convert each point to galactic coordinates.
Calculate the galactic coordinates of the edges of three disks centered on
each point.  Write the point and its disks to a table on disk.

For efficiency, each worker process writes to its own separate table on
disk. The table is a sequence of pickles; each pickled object is a tuple

    (eclipse, has_nuv, has_fuv, disks)

    eclipse = int:  eclipse number
    has_nuv = bool: this eclipse has valid NUV image data
    has_fuv = bool: this eclipse has valid FUV image data
    disks = [wkb_350, wkb_370, wkb_400]
    wkb_nnn = bytes: WKB representation of the disk for detector size nnn

As this format is fairly verbose, the tables on disk are automatically
compressed with gzip.
"""

import argparse
import gzip
import multiprocessing
import os
import pickle
import pickletools
import struct
import sys
import time

from datetime import timedelta
from math import pi as PI
from pathlib import Path

from astropy.coordinates import SkyCoord
from cartopy import crs
from gPhoton.constants import DETSIZE as DETSIZE_400
from pyarrow import parquet

import numpy as np
import shapely

# Conversions between radians and degrees
DEG_TO_RAD = PI/180.0
RAD_TO_DEG = 180.0/PI

# Narrower definitions of the detector size
DETSIZE_370 = DETSIZE_400 * 370 / 400
DETSIZE_350 = DETSIZE_400 * 350 / 400

# Celestial sphere and standard equatorial sky coordinate system
CEL_SPHERE = crs.Globe(
    ellipse=None,
    # these axes produce a sphere whose projections have 1 map unit = 1 degree,
    # which is what we need
    semimajor_axis=180/PI,
    semiminor_axis=180/PI,
)
CRS_GALACTIC = crs.Geodetic(globe=CEL_SPHERE)
PC_GALACTIC = crs.PlateCarree(globe=CEL_SPHERE)

# Shapely has no concept of arcs; curves must be approximated using a
# sequence of lines.  The polygon generated by Point(x,y).buffer(r) is
# guaranteed to be inscribed within a true circle of radius r.  The
# approximation can be made more precise by increasing this parameter,
# which is the number of segments to use for each quarter-circle.
#
# At QUAD_SEGS = 72, the approximation of a circle with radius
# APERTURE_RADIUS has area 1262 cdelt^2 units smaller than a true
# circle with that radius; this is a relative error of 0.008%,
# which we should be able to live with.
QUAD_SEGS = 72


START_TIME = None
def progress(msg: str) -> None:
    now = time.monotonic()

    global START_TIME
    if START_TIME is None:
        START_TIME = now

    elapsed = timedelta(seconds=now - START_TIME)
    sys.stderr.write(f"[{elapsed}]  {msg}\n")


def ok_aspect_fixes(aspect):
    """Extract the time of each aspect fix from the aspect table,
       calculate whether each aspect fix is considered part of the
       observation, and return (ra, dec) for each fix that is
       considered part of the observation."""
    # if the mysterious 'flags' number is odd, it means this aspect
    # record should not be considered part of the observation.
    # the full set of reasons for flagging an aspect record is not
    # known, but the most common reasons are that the detector hadn't
    # yet come up to operating voltage, or that the telescope was
    # carrying out a high-speed slew during that time step.
    ok = aspect["flags"].to_numpy() & 1 == 0

    # we also distrust aspect records immediately before and after a
    # flagged aspect record; the first record in 'aspect' is assumed
    # to be preceded by a flagged record, and the last record is
    # assumed to be followed by a flagged record
    ok &= np.concat([[False], ok[:-1]])
    ok &= np.concat([ok[1:], [False]])

    # we also distrust aspect records whose time step is not 1
    times = aspect["time"].to_numpy()
    ok[1:] &= np.isclose(times[1:] - times[:-1], 1.0)

    # RA should be in (-180°, 180°]; wrap it if necessary.
    ra = aspect["ra"].to_numpy()[ok]
    ra = np.fmod(ra + 180.0, 360.0) - 180.0

    # Thankfully, declination is always in [-90°, 90°] already;
    # correcting that would be quite a bit more trouble, as
    # declination wraparound affects RA as well and the most
    # straightforward way to handle it involves an expensive
    # trigonometric calculation.
    dec = aspect["dec"].to_numpy()[ok]

    return SkyCoord(ra, dec, frame="icrs", unit="deg")


def crunch_points_for_eclipse(task, ofp, aperture_disks):
    """Process the aspect table for a single eclipse into a series of
       GeometryCollection objects, as described in the module docstring,
       and write them to the file OFP.

       TASK is expected to be a 3-tuple: (eclipse, metadata, aspect)
       where ECLIPSE is the eclipse number,
             METADATA is a pandas.Series with fields 'has_nuv' and 'has_fuv',
             ASPECT is a pandas.Table with columns (ra, dec, time, flags).
    """

    (eclipse, metadata, aspect) = task
    assert eclipse <= 0xFFFF

    points = ok_aspect_fixes(aspect).galactic

    # For each point (l, b), back-project each of the 'aperture_disks'
    # from an azimuthal equidistant projection centered on (l, b), to the
    # celestial sphere.
    globe = CEL_SPHERE
    pc = PC_GALACTIC
    AzEq = crs.AzimuthalEquidistant

    for l, b in zip(points.l.value, points.b.value):
        projected = pc.project_geometry(
            aperture_disks,
            AzEq(l, b, globe=globe)
        )
        wkbs = [
            shapely.to_wkb(
                disk.buffer(0),
                output_dimension=2,
                byte_order=1,
                flavor="iso"
            )
            for disk in projected.geoms
        ]

        has_nuv = metadata.has_nuv.item()
        has_fuv = metadata.has_fuv.item()

        ofp.write(pickletools.optimize(pickle.dumps(
            (eclipse, has_nuv, has_fuv, wkbs),
            protocol = 4
        )))


def crunch_points_worker(inq, ofname):
    """Main worker loop.  INQ is a multiprocessing.Connection which will
       yield aspect tables for eclipses.  OFNAME is where the processed
       data should be written."""

    # disks with the radiuses used for the detector aperture, in
    # degrees, centered on the plane origin; as a micro-optimization,
    # compute these only once per worker
    aperture_disks = shapely.GeometryCollection([
        shapely.Point(0, 0).buffer(DETSIZE_350/2, quad_segs=QUAD_SEGS),
        shapely.Point(0, 0).buffer(DETSIZE_370/2, quad_segs=QUAD_SEGS),
        shapely.Point(0, 0).buffer(DETSIZE_400/2, quad_segs=QUAD_SEGS),
    ])
    with gzip.open(ofname, "wb") as ofp:
        try:
            while True:
                task = inq.recv()
                if task is None:
                    break
                crunch_points_for_eclipse(task, ofp, aperture_disks)
        except EOFError:
            pass
        ofp.flush()


def start_worker(outdir, i):
    """Start one worker process"""
    qr, qw = multiprocessing.Pipe(False)
    ofname = outdir / f"disks-{i:02}.gz"
    worker = multiprocessing.Process(
        target=crunch_points_worker,
        args=(qr, ofname)
    )
    worker.start()
    return (worker, qw)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("aspect", type=Path)
    ap.add_argument("metadata", type=Path)
    ap.add_argument("outdir", type=Path)
    args = ap.parse_args()
    aspect = args.aspect
    metadata = args.metadata
    outdir = args.outdir

    outdir.mkdir(parents=True, exist_ok=True)

    # fork workers _before_ reading the aspect table to avoid
    # bloating up the workers' memory usage
    progress("starting workers")
    workers = [start_worker(outdir, i) for i in range(os.process_cpu_count())]
    try:
        progress("reading aspect")
        all_aspect = parquet.read_table(
            args.aspect,
            columns=["eclipse", "time", "flags", "ra", "dec"],
        ).to_pandas().groupby("eclipse")

        progress("reading eclipse metadata")
        all_metadata = parquet.read_table(
            args.metadata,
            columns=["eclipse", "nuv_det_on_time", "nuv_has_raw6",
                     "fuv_det_on_time", "fuv_has_raw6",],
            filters=[("has_aspect", "==", True)]
        ).to_pandas().assign(
            has_nuv = lambda x: x.nuv_has_raw6 & (x.nuv_det_on_time > 0),
            has_fuv = lambda x: x.fuv_has_raw6 & (x.fuv_det_on_time > 0),
        ).drop(
            ["nuv_det_on_time", "nuv_has_raw6",
             "fuv_det_on_time", "fuv_has_raw6"],
            axis = 1,
        ).set_index("eclipse")

        progress("distributing eclipses")
        n = 0
        for eclipse, aspect in all_aspect:
            metadata = all_metadata.loc[eclipse]
            workers[n % len(workers)][1].send((eclipse, metadata, aspect))
            n += 1
            if n % 1000 == 0:
                progress(f"... {n}")
        progress(f"... {n}.")

        progress("waiting for completion")
        n = 0
        for _, q in workers:
            q.send(None)
            q.close()
        while workers:
            w, _ = workers.pop()
            w.join()
            n += 1
            progress(f"... {n}")

    finally:
        progress("cleaning up")
        for worker, inq in workers:
            inq.close()
            worker.terminate()
            worker.join()

if __name__ == "__main__":
    main()
