"""Produce a diagnostic plot of the data generated by phase 2 (grid.py)."""

import argparse
import gzip
import pickle
import sys
import time

from datetime import timedelta
from math import pi as PI
from pathlib import Path

import numpy as np
import matplotlib.pyplot as plt

from cartopy import crs

CEL_SPHERE = crs.Globe(
    ellipse=None,
    # these axes produce a sphere whose projections have 1 map unit = 1 degree,
    # which is what we need
    semimajor_axis=180/PI,
    semiminor_axis=180/PI,
)
CRS_GALACTIC = crs.Geodetic(globe=CEL_SPHERE)
PC_GALACTIC = crs.PlateCarree(globe=CEL_SPHERE)


START_TIME = None
def progress(msg: str) -> None:
    now = time.monotonic()

    global START_TIME
    if START_TIME is None:
        START_TIME = now

    elapsed = timedelta(seconds=now - START_TIME)
    sys.stderr.write(f"[{elapsed}]  {msg}\n")


def extract_points(picklefile):
    with gzip.open(picklefile, "rb") as fp:
        blob = pickle.load(fp)

    return np.fromiter(
        ((pt.x, pt.y) for pt in blob.geometries),
        dtype=np.dtype((float, 2)),
        count=len(blob.geometries)
    )


def plot(plot_file, grid_dir, width, height):
    fig = plt.figure(figsize=(width, height), dpi=300)
    try:
        ax = fig.subplots(1, 1, subplot_kw={
            "xlim": (-180, 180),
            "ylim": (-90, 90),
            "projection": crs.Mollweide(globe=CEL_SPHERE)
        })
        pixelsize = (72./fig.dpi)**2

        for sector in grid_dir.glob("grid-*.pickle.gz"):
            progress(f"{sector}: loading...")
            pts = extract_points(sector)
            progress(f"{sector}: plotting...")
            ax.scatter(
                pts[:, 0], pts[:, 1],
                marker='o', lw=0, s=pixelsize,
                transform=PC_GALACTIC,
            )

        progress(f"writing...")
        fig.savefig(plot_file)
    finally:
        plt.close(fig)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("plot_file", type=Path)
    ap.add_argument("grid_dir", type=Path)
    ap.add_argument("width", type=float)
    ap.add_argument("height", type=float)

    a = ap.parse_args()
    plot(a.plot_file, a.grid_dir, a.width, a.height)
    progress("done")


main()
